// The world-cuisine list backing the admin form's searchable autocomplete.
// Copied verbatim from the design export (design/Flip's Kitchen.dc.html →
// `cuisineOptions`) so the picker offers the same ~50 options. Custom entries are
// still allowed — the field writes the free-text `cuisine` column either way.
export const CUISINES = [
  'Filipino',
  'Thai',
  'Japanese',
  'Chinese',
  'Korean',
  'Vietnamese',
  'Indonesian',
  'Malaysian',
  'Indian',
  'Sri Lankan',
  'Nepali',
  'Burmese',
  'Cambodian',
  'Laotian',
  'Singaporean',
  'Taiwanese',
  'American',
  'Tex-Mex',
  'Cajun / Creole',
  'Hawaiian',
  'Mexican',
  'Peruvian',
  'Brazilian',
  'Argentine',
  'Caribbean',
  'Cuban',
  'Italian',
  'French',
  'Spanish',
  'Portuguese',
  'Greek',
  'German',
  'British',
  'Irish',
  'Russian',
  'Polish',
  'Hungarian',
  'Georgian',
  'Turkish',
  'Lebanese',
  'Israeli',
  'Persian (Iranian)',
  'Moroccan',
  'Tunisian',
  'Egyptian',
  'Ethiopian',
  'Nigerian',
  'South African',
  'Fusion',
  'Other',
] as const
