// Recipe data for Flip's Kitchen — Filipino / Thai / Japanese
// Plain ES module, imported dynamically by the app DC (doubles as the loading state).

export const filterChips = [
  "Chicken", "Pork", "Beef", "Seafood", "Noodles",
  "Rice", "Coconut", "Vegetarian", "Spicy", "Quick",
];

export const recipes = [
  {
    id: "chicken-adobo",
    title: "Chicken Adobo",
    cuisine: "Filipino",
    description:
      "The everyday classic — chicken braised low and slow in soy, vinegar, garlic and bay until glossy and deeply savory.",
    prep: 15, cook: 45, total: 60, servings: 4, difficulty: 2,
    tags: ["Chicken", "Rice", "Weeknight"],
    youtube: "chicken adobo recipe",
    gallery: true,
    ingredients: [
      { qty: "900", unit: "g", name: "chicken thighs, bone-in" },
      { qty: "1/2", unit: "cup", name: "soy sauce" },
      { qty: "1/3", unit: "cup", name: "cane or white vinegar" },
      { qty: "1", unit: "whole", name: "garlic head, crushed" },
      { qty: "3", unit: "pcs", name: "dried bay leaves" },
      { qty: "1", unit: "tsp", name: "whole black peppercorns" },
      { qty: "1", unit: "cup", name: "water" },
      { qty: "1", unit: "tbsp", name: "brown sugar" },
    ],
    steps: [
      { text: "Marinate the chicken in soy sauce and crushed garlic for at least 30 minutes (overnight is better).", photo: false },
      { text: "Sear the chicken skin-side down in a hot pot until deeply browned, then set aside.", photo: true },
      { text: "Pour in the marinade, water, bay leaves and peppercorns. Bring to a boil, then simmer covered for 25 minutes.", photo: false },
      { text: "Add the vinegar and do NOT stir — let it come back to a boil for 2 minutes to cook off the sharpness.", photo: false },
      { text: "Stir in the brown sugar, then reduce the sauce uncovered until it clings and turns glossy.", photo: true },
      { text: "Rest 5 minutes and serve over hot steamed rice, spooning the sauce generously.", photo: false },
    ],
  },
  {
    id: "sinigang-baboy",
    title: "Sinigang na Baboy",
    cuisine: "Filipino",
    description:
      "A bright, sour tamarind pork soup crowded with vegetables — the ultimate comfort bowl on a rainy day.",
    prep: 20, cook: 70, total: 90, servings: 6, difficulty: 3,
    tags: ["Pork", "Soup", "Sour"],
    youtube: null, gallery: false,
    ingredients: [
      { qty: "1", unit: "kg", name: "pork belly or ribs, cubed" },
      { qty: "1", unit: "pouch", name: "tamarind soup base (or fresh sampalok)" },
      { qty: "2", unit: "pcs", name: "tomatoes, quartered" },
      { qty: "1", unit: "pc", name: "onion, quartered" },
      { qty: "1", unit: "bunch", name: "kangkong (water spinach)" },
      { qty: "2", unit: "pcs", name: "radish, sliced" },
      { qty: "8", unit: "pcs", name: "string beans, cut" },
      { qty: "2", unit: "pcs", name: "long green chili" },
    ],
    steps: [
      { text: "Boil pork with onion and tomatoes for about 45 minutes until fork-tender, skimming off the foam.", photo: false },
      { text: "Add radish and string beans; simmer until just tender.", photo: false },
      { text: "Stir in the tamarind base and season with fish sauce to taste.", photo: false },
      { text: "Drop in the chili and kangkong last, cook 1 minute so the greens stay bright.", photo: false },
      { text: "Serve piping hot with a side of rice and extra fish sauce with chili.", photo: false },
    ],
  },
  {
    id: "pancit-bihon",
    title: "Pancit Bihon",
    cuisine: "Filipino",
    description:
      "Thin rice noodles tossed with chicken, shrimp and a rainbow of vegetables — the dish that means a celebration.",
    prep: 25, cook: 20, total: 45, servings: 8, difficulty: 2,
    tags: ["Noodles", "Chicken", "Party"],
    youtube: null, gallery: false,
    ingredients: [
      { qty: "400", unit: "g", name: "bihon rice noodles" },
      { qty: "2", unit: "pcs", name: "chicken breast, shredded" },
      { qty: "1", unit: "cup", name: "cabbage, shredded" },
      { qty: "1", unit: "pc", name: "carrot, julienned" },
      { qty: "3", unit: "cloves", name: "garlic, minced" },
      { qty: "3", unit: "tbsp", name: "soy sauce" },
      { qty: "3", unit: "cups", name: "chicken broth" },
      { qty: "2", unit: "stalks", name: "celery, sliced" },
    ],
    steps: [
      { text: "Soak the bihon noodles in warm water for 10 minutes, then drain.", photo: false },
      { text: "Sauté garlic, then cook the chicken until no longer pink. Add vegetables and stir-fry briefly.", photo: false },
      { text: "Pour in broth and soy sauce, bring to a simmer.", photo: false },
      { text: "Add the noodles and toss constantly until they absorb the liquid and turn tender.", photo: false },
      { text: "Finish with green onions and serve with calamansi wedges.", photo: false },
    ],
  },
  {
    id: "kare-kare",
    title: "Kare-Kare",
    cuisine: "Filipino",
    description:
      "A rich oxtail and vegetable stew in a thick peanut sauce, served with a salty punch of bagoong.",
    prep: 30, cook: 120, total: 150, servings: 6, difficulty: 4,
    tags: ["Beef", "Peanut", "Feast"],
    youtube: null, gallery: false,
    ingredients: [
      { qty: "1.2", unit: "kg", name: "oxtail, cut into segments" },
      { qty: "3/4", unit: "cup", name: "peanut butter" },
      { qty: "1/4", unit: "cup", name: "toasted ground rice" },
      { qty: "1", unit: "bunch", name: "bok choy or pechay" },
      { qty: "1", unit: "pc", name: "eggplant, sliced" },
      { qty: "1", unit: "bundle", name: "string beans" },
      { qty: "1", unit: "pc", name: "banana heart (optional)" },
      { qty: "3", unit: "tbsp", name: "bagoong (shrimp paste), to serve" },
    ],
    steps: [
      { text: "Simmer oxtail for about 2 hours until very tender, reserving the broth.", photo: false },
      { text: "Whisk peanut butter and toasted ground rice into the hot broth until thickened.", photo: false },
      { text: "Return the oxtail and simmer gently to coat in the sauce.", photo: false },
      { text: "Blanch the vegetables separately so they keep their color and bite.", photo: false },
      { text: "Plate the stew, arrange the vegetables on top, and serve with sautéed bagoong on the side.", photo: false },
    ],
  },
  {
    id: "lumpiang-shanghai",
    title: "Lumpiang Shanghai",
    cuisine: "Filipino",
    description:
      "Slim, crackly pork spring rolls fried golden — impossible to eat just one, always the first tray emptied.",
    prep: 40, cook: 20, total: 60, servings: 10, difficulty: 3,
    tags: ["Pork", "Fried", "Party"],
    youtube: null, gallery: false,
    ingredients: [
      { qty: "500", unit: "g", name: "ground pork" },
      { qty: "1", unit: "pc", name: "carrot, finely minced" },
      { qty: "4", unit: "cloves", name: "garlic, minced" },
      { qty: "1", unit: "pc", name: "egg" },
      { qty: "30", unit: "pcs", name: "spring roll wrappers" },
      { qty: "3", unit: "stalks", name: "green onion, chopped" },
      { qty: "1", unit: "tsp", name: "salt and pepper" },
      { qty: "2", unit: "cups", name: "oil, for frying" },
    ],
    steps: [
      { text: "Mix pork, carrot, garlic, green onion, egg and seasoning until well combined.", photo: false },
      { text: "Spoon a thin line of filling onto each wrapper and roll tightly, sealing the edge with water.", photo: false },
      { text: "Chill the rolls for 15 minutes so they hold their shape.", photo: false },
      { text: "Fry in batches over medium heat until golden and crisp, about 4 minutes.", photo: false },
      { text: "Drain, slice, and serve with sweet chili sauce.", photo: false },
    ],
  },
  {
    id: "chicken-tinola",
    title: "Chicken Tinola",
    cuisine: "Filipino",
    description:
      "A clean, ginger-forward chicken soup with green papaya and chili leaves — light, nourishing, and quick.",
    prep: 15, cook: 35, total: 50, servings: 4, difficulty: 1,
    tags: ["Chicken", "Soup", "Ginger"],
    youtube: null, gallery: false,
    ingredients: [
      { qty: "1", unit: "kg", name: "chicken, cut into pieces" },
      { qty: "1", unit: "thumb", name: "ginger, sliced into strips" },
      { qty: "1", unit: "pc", name: "green papaya or sayote, wedged" },
      { qty: "1", unit: "bunch", name: "chili or malunggay leaves" },
      { qty: "1", unit: "pc", name: "onion, chopped" },
      { qty: "4", unit: "cloves", name: "garlic, minced" },
      { qty: "2", unit: "tbsp", name: "fish sauce" },
      { qty: "5", unit: "cups", name: "water" },
    ],
    steps: [
      { text: "Sauté garlic, onion and ginger until fragrant.", photo: false },
      { text: "Add the chicken and sear lightly, then season with fish sauce.", photo: false },
      { text: "Pour in water and simmer 25 minutes until the chicken is tender.", photo: false },
      { text: "Add the papaya and cook until just soft.", photo: false },
      { text: "Turn off the heat and stir in the leaves. Serve hot.", photo: false },
    ],
  },
  {
    id: "pad-thai",
    title: "Pad Thai",
    cuisine: "Thai",
    description:
      "Springy rice noodles wok-tossed with shrimp, egg and a sweet-sour-salty tamarind sauce, showered with peanuts.",
    prep: 25, cook: 15, total: 40, servings: 4, difficulty: 3,
    tags: ["Noodles", "Seafood", "Spicy", "Quick"],
    youtube: null, gallery: false,
    ingredients: [
      { qty: "250", unit: "g", name: "flat rice noodles" },
      { qty: "300", unit: "g", name: "shrimp, peeled" },
      { qty: "2", unit: "pcs", name: "eggs" },
      { qty: "3", unit: "tbsp", name: "tamarind paste" },
      { qty: "2", unit: "tbsp", name: "fish sauce" },
      { qty: "2", unit: "tbsp", name: "palm sugar" },
      { qty: "1", unit: "cup", name: "bean sprouts" },
      { qty: "1/3", unit: "cup", name: "roasted peanuts, crushed" },
    ],
    steps: [
      { text: "Soak the noodles in warm water until pliable, then drain.", photo: false },
      { text: "Whisk tamarind, fish sauce and palm sugar into a sauce.", photo: false },
      { text: "Stir-fry the shrimp in a very hot wok, push aside, and scramble the eggs.", photo: false },
      { text: "Add the noodles and sauce, tossing until glossy and tender.", photo: false },
      { text: "Fold in bean sprouts, top with peanuts and lime, and serve at once.", photo: false },
    ],
  },
  {
    id: "green-curry",
    title: "Thai Green Curry",
    cuisine: "Thai",
    description:
      "Fragrant coconut curry with chicken, Thai basil and eggplant — bright, herbal heat balanced by creamy coconut.",
    prep: 20, cook: 25, total: 45, servings: 4, difficulty: 3,
    tags: ["Chicken", "Coconut", "Spicy"],
    youtube: null, gallery: false,
    ingredients: [
      { qty: "500", unit: "g", name: "chicken thigh, sliced" },
      { qty: "3", unit: "tbsp", name: "green curry paste" },
      { qty: "400", unit: "ml", name: "coconut milk" },
      { qty: "1", unit: "cup", name: "Thai eggplant, quartered" },
      { qty: "1", unit: "handful", name: "Thai basil leaves" },
      { qty: "2", unit: "pcs", name: "kaffir lime leaves" },
      { qty: "1", unit: "tbsp", name: "fish sauce" },
      { qty: "1", unit: "tsp", name: "palm sugar" },
    ],
    steps: [
      { text: "Fry the curry paste in the thick top of the coconut milk until the oil splits and it smells fragrant.", photo: false },
      { text: "Add the chicken and stir to coat.", photo: false },
      { text: "Pour in the rest of the coconut milk with lime leaves; simmer 10 minutes.", photo: false },
      { text: "Add eggplant and cook until tender; season with fish sauce and sugar.", photo: false },
      { text: "Finish with Thai basil and serve with jasmine rice.", photo: false },
    ],
  },
  {
    id: "tom-yum-goong",
    title: "Tom Yum Goong",
    cuisine: "Thai",
    description:
      "The iconic hot-and-sour shrimp soup — lemongrass, galangal and lime bright enough to wake up the whole table.",
    prep: 15, cook: 25, total: 40, servings: 4, difficulty: 2,
    tags: ["Seafood", "Soup", "Spicy", "Quick"],
    youtube: null, gallery: false,
    ingredients: [
      { qty: "400", unit: "g", name: "large shrimp, shell-on" },
      { qty: "2", unit: "stalks", name: "lemongrass, bruised" },
      { qty: "4", unit: "slices", name: "galangal" },
      { qty: "5", unit: "pcs", name: "kaffir lime leaves" },
      { qty: "200", unit: "g", name: "mushrooms, halved" },
      { qty: "3", unit: "tbsp", name: "fish sauce" },
      { qty: "3", unit: "tbsp", name: "lime juice" },
      { qty: "5", unit: "pcs", name: "bird's eye chili, crushed" },
    ],
    steps: [
      { text: "Simmer the shrimp shells in water for 10 minutes to build a quick stock, then strain.", photo: false },
      { text: "Add lemongrass, galangal and lime leaves; simmer 5 minutes.", photo: false },
      { text: "Add mushrooms and shrimp, cook just until the shrimp curl and turn pink.", photo: false },
      { text: "Off the heat, season with fish sauce, lime juice and chili — taste for a hot-sour-salty balance.", photo: false },
      { text: "Garnish with cilantro and serve immediately.", photo: false },
    ],
  },
  {
    id: "mango-sticky-rice",
    title: "Mango Sticky Rice",
    cuisine: "Thai",
    description:
      "Warm coconut-soaked glutinous rice with ripe mango and a salty-sweet coconut drizzle — the perfect finish.",
    prep: 10, cook: 40, total: 50, servings: 4, difficulty: 2,
    tags: ["Rice", "Coconut", "Dessert", "Vegetarian"],
    youtube: null, gallery: false,
    ingredients: [
      { qty: "1", unit: "cup", name: "glutinous rice, soaked" },
      { qty: "1", unit: "cup", name: "coconut milk" },
      { qty: "1/3", unit: "cup", name: "sugar" },
      { qty: "1/2", unit: "tsp", name: "salt" },
      { qty: "2", unit: "pcs", name: "ripe mangoes, sliced" },
      { qty: "1", unit: "tbsp", name: "toasted mung beans or sesame" },
    ],
    steps: [
      { text: "Steam the soaked glutinous rice for 25 minutes until tender.", photo: false },
      { text: "Warm coconut milk with sugar and salt (don't boil), reserving a little for drizzling.", photo: false },
      { text: "Fold most of the coconut mixture into the hot rice and let it sit 15 minutes to absorb.", photo: false },
      { text: "Plate the rice with sliced mango.", photo: false },
      { text: "Drizzle with reserved coconut sauce and scatter toasted mung beans on top.", photo: false },
    ],
  },
  {
    id: "chicken-katsu-curry",
    title: "Chicken Katsu Curry",
    cuisine: "Japanese",
    description:
      "Crunchy panko cutlets over rice, blanketed in a mellow, faintly sweet Japanese curry sauce.",
    prep: 25, cook: 35, total: 60, servings: 4, difficulty: 3,
    tags: ["Chicken", "Rice", "Comfort"],
    youtube: null, gallery: false,
    ingredients: [
      { qty: "4", unit: "pcs", name: "chicken breasts" },
      { qty: "2", unit: "cups", name: "panko breadcrumbs" },
      { qty: "2", unit: "pcs", name: "eggs, beaten" },
      { qty: "1", unit: "box", name: "Japanese curry roux" },
      { qty: "1", unit: "pc", name: "onion, sliced" },
      { qty: "2", unit: "pcs", name: "carrots, chopped" },
      { qty: "2", unit: "pcs", name: "potatoes, cubed" },
      { qty: "4", unit: "cups", name: "steamed rice, to serve" },
    ],
    steps: [
      { text: "Simmer onion, carrot and potato until soft, then melt in the curry roux to make the sauce.", photo: false },
      { text: "Pound the chicken to an even thickness and season.", photo: false },
      { text: "Dredge each cutlet in flour, egg, then panko.", photo: false },
      { text: "Fry until deep golden and cooked through; rest, then slice.", photo: false },
      { text: "Serve the sliced katsu over rice with curry sauce ladled alongside.", photo: false },
    ],
  },
  {
    id: "miso-ramen",
    title: "Miso Ramen",
    cuisine: "Japanese",
    description:
      "A deeply savory miso-based broth with springy noodles, chashu, soft egg and all the toppings you love.",
    prep: 30, cook: 45, total: 75, servings: 2, difficulty: 4,
    tags: ["Noodles", "Pork", "Soup"],
    youtube: null, gallery: false,
    ingredients: [
      { qty: "2", unit: "portions", name: "fresh ramen noodles" },
      { qty: "3", unit: "tbsp", name: "miso paste" },
      { qty: "4", unit: "cups", name: "pork or chicken stock" },
      { qty: "2", unit: "cloves", name: "garlic, grated" },
      { qty: "1", unit: "thumb", name: "ginger, grated" },
      { qty: "4", unit: "slices", name: "chashu pork" },
      { qty: "2", unit: "pcs", name: "soft-boiled eggs, halved" },
      { qty: "2", unit: "stalks", name: "green onion, sliced" },
    ],
    steps: [
      { text: "Bloom garlic and ginger in a little oil, then whisk in the miso paste.", photo: false },
      { text: "Add the stock and simmer gently for 15 minutes — do not boil hard.", photo: false },
      { text: "Cook the ramen noodles separately to package time and drain well.", photo: false },
      { text: "Divide the noodles into bowls and ladle the hot broth over them.", photo: false },
      { text: "Top with chashu, egg, green onion and corn, and serve immediately.", photo: false },
    ],
  },
];
